-- =============================================================
-- go-frame user 模块 DDL — PostgreSQL 12+
-- 表：sys_privilege_constant / sys_department / sys_role /
--     sys_user / sys_user_role
-- 约定（与 MySQL 版语义一致）：
--   * 逻辑删除列 deleted（false 未删 / true 已删），DAO 侧 logicDel 自动过滤
--   * 用户删除时 username/phone 置 NULL，规避唯一索引冲突
--   * class 类型映射：String→varchar、Int32→integer、Bool→boolean、
--     Time→timestamp(3)、ArrString→text[]（PG 原生数组）、
--     MapString→jsonb
--   * 角色 id=0 保留给内置超级管理员，故 sys_role.id 不自增
-- =============================================================

-- ---------- 权限码字典 ----------
CREATE TABLE IF NOT EXISTS sys_privilege_constant (
  id   varchar(128) NOT NULL,
  name varchar(128) NOT NULL DEFAULT '',
  type varchar(64)  NOT NULL DEFAULT '',
  sort integer      NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);
COMMENT ON TABLE sys_privilege_constant IS '权限码字典';

-- ---------- 部门（树形） ----------
CREATE TABLE IF NOT EXISTS sys_department (
  id          bigint       GENERATED BY DEFAULT AS IDENTITY,
  no          varchar(64)  NOT NULL DEFAULT '',
  name        varchar(64)  NOT NULL DEFAULT '',
  description varchar(512) NOT NULL DEFAULT '',
  parent      bigint       NOT NULL DEFAULT 0,
  immutable   boolean      NOT NULL DEFAULT false,
  extend      jsonb        DEFAULT '{}'::jsonb,
  deleted     boolean      NOT NULL DEFAULT false,
  createdt    timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedt    timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_department_parent FOREIGN KEY (parent) REFERENCES sys_department (id)
);
CREATE INDEX IF NOT EXISTS idx_department_parent ON sys_department (parent);
CREATE INDEX IF NOT EXISTS idx_department_no ON sys_department (no);
COMMENT ON TABLE sys_department IS '部门';
COMMENT ON COLUMN sys_department.parent IS '父部门id，0 为根';

-- ---------- 角色（全局，不绑部门；数据范围只由用户部门决定） ----------
-- id 用 GENERATED BY DEFAULT AS IDENTITY：自增从 1 开始，同时允许显式插入
-- id=0 的内置超级管理员角色（model 中 auto 标签只让 PG RETURNING 回填自增值）。
CREATE TABLE IF NOT EXISTS sys_role (
  id          bigint       GENERATED BY DEFAULT AS IDENTITY,
  name        varchar(64)  NOT NULL DEFAULT '',
  description varchar(512) NOT NULL DEFAULT '',
  privileges  text[]       NOT NULL DEFAULT '{}',
  immutable   boolean      NOT NULL DEFAULT false,
  extend      jsonb        DEFAULT '{}'::jsonb,
  deleted     boolean      NOT NULL DEFAULT false,
  createdt    timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedt    timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
COMMENT ON TABLE sys_role IS '角色';
COMMENT ON COLUMN sys_role.id IS '0 保留给内置超级管理员角色';

-- ---------- 用户 ----------
CREATE TABLE IF NOT EXISTS sys_user (
  id         bigint        GENERATED BY DEFAULT AS IDENTITY,
  department bigint        DEFAULT NULL,
  username   varchar(64)   DEFAULT NULL,
  name       varchar(64)   NOT NULL DEFAULT '',
  phone      varchar(32)   DEFAULT NULL,
  pwd        varchar(255)  NOT NULL DEFAULT '',
  gender     integer       NOT NULL DEFAULT 0,
  image      varchar(1024) NOT NULL DEFAULT '',
  address    varchar(512)  NOT NULL DEFAULT '',
  status     integer       NOT NULL DEFAULT 0,
  immutable  boolean       NOT NULL DEFAULT false,
  extend     jsonb         DEFAULT '{}'::jsonb,
  deleted    boolean       NOT NULL DEFAULT false,
  createdt   timestamp(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedt   timestamp(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_user_department FOREIGN KEY (department) REFERENCES sys_department (id)
);
-- 逻辑删除后 username/phone 被置 NULL，PG 唯一索引允许多行 NULL
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_username ON sys_user (username);
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_phone ON sys_user (phone);
CREATE INDEX IF NOT EXISTS idx_user_department ON sys_user (department);
CREATE INDEX IF NOT EXISTS idx_user_name ON sys_user (name);
COMMENT ON TABLE sys_user IS '用户';
COMMENT ON COLUMN sys_user.pwd IS 'bcrypt 密码哈希';
COMMENT ON COLUMN sys_user.extend IS '扩展字段，如 privilegeExclude 权限剔除';

-- ---------- 用户-角色关联（多对多中间表） ----------
CREATE TABLE IF NOT EXISTS sys_user_role (
  userid   bigint      NOT NULL,
  roleid   bigint      NOT NULL,
  createdt timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (userid, roleid),
  CONSTRAINT fk_user_role_user FOREIGN KEY (userid) REFERENCES sys_user (id),
  CONSTRAINT fk_user_role_role FOREIGN KEY (roleid) REFERENCES sys_role (id)
);
CREATE INDEX IF NOT EXISTS idx_user_role_roleid ON sys_user_role (roleid);
COMMENT ON TABLE sys_user_role IS '用户-角色关联';
